//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 28.05.2022 19:44:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace GuideDomain
{
    public partial class GuideEntity {

        public GuideEntity()
        {
            this.GuideRows = new List<GuideRow>();
            this.GuideColls = new List<GuideColl>();
            OnCreated();
        }

        public virtual System.Guid Id
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual System.Guid GuidesListId
        {
            get;
            set;
        }

        public virtual GuidesList GuidesList
        {
            get;
            set;
        }

        public virtual IList<GuideRow> GuideRows
        {
            get;
            set;
        }

        public virtual IList<GuideColl> GuideColls
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
