//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 28.05.2022 19:44:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace GuideDomain
{
    public partial class GuideRow {

        public GuideRow()
        {
            OnCreated();
        }

        public virtual System.Guid Id
        {
            get;
            set;
        }

        public virtual System.Guid GuideEntityId
        {
            get;
            set;
        }

        public virtual GuideEntity GuideEntity
        {
            get;
            set;
        }

        public virtual GuideRowCollData GuideRowCollData
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
